name: Test Automation WorkFlow

on:
  push:
    branches: [ "master" ]

  pull_request:
    branches: [ "master" ]

  schedule:
    - cron: "0 13 * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven

      - name: Running Test Automation Framework with Maven
        run: mvn test -X -Dbrowser=chrome -DisLamdaTest=true -DisHeadless=false

      - name: Upload Test logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-logs
          path: logs/
          
      - name: Upload Screenshot as Artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: screenshots
          path: screenshots/

      - name: Upload HTML Reports as Artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-report
          path: report.html

      - name: Test Execution Status
        run: echo "Test Execution Completed"

      - name: Copy Report to gh-pages Folder
        if: always()
        run: |
         mkdir -p public/extent-reports
         cp report.html public/extent-reports/
          cp -R screenshots public/extent-reports/
         ls -R public
      - name: Deploy
        if: always()
        uses: JamesIves/github-pages-deploy-action@v4
      with:
    folder: public/extent-reports/
    token: ${{ secrets.PAT123 }}
    branch: gh-pages
    clean: true

        
